apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    run: backend-user
spec:
  selector:
    run: backend-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080